name: Sync Fork

on:
  schedule:
    - cron: '* * * * *'  # Run every 6 hours
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - develop  # Change to your main branch if needed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "faisalsp"
          git config --global user.email "faisal@twmg.com.au"

      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/stevanus-giga/dating-guide-vue.git
          git fetch upstream
          git checkout -b develop  # Ensure you are on the correct branch
          git merge upstream/develop --no-edit --allow-unrelated-histories

      - name: Push Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git push https://$PAT_TOKEN@github.com/faisalsp/dating-guide-vue.git develop
